### ISSUE TITLE
Can't download `Python support package for Android`

### ISSUE THREAD

**Issue by gtf35** [beeware/briefcase-android-gradle-template#38]
**Describe the bug**
Can't download `Python support package for Android`, the link may be wrong( `https://github.com/beeware/briefcase-android-gradle-template/tree/3.8#id1`)

**To Reproduce**
1. Click `Download the Python support package for Android`_,  in readme
2. There is nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/22125696/139110886-fc6f02b3-0b46-4a18-bdba-58e5dd019f2e.png)

**Comment by freakboy3742** [comment]
Thanks for the report - it was a markup problem on the README. I've corrected this problem.
