### ISSUE TITLE
Template Does Not Support 3.10

### ISSUE THREAD

**Issue by djaychela** [beeware/briefcase-android-gradle-template#46]
**Describe the bug**
The template doesn't support Python 3.10 projects.

**To Reproduce**
`briefcase create android`

**Expected behavior**
Android App to be created

**Environment:**
 - Operating System: macOS
 - Python version: 3.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0dev30

**Additional context**
Encountered while following the tutorial for Briefcase - https://docs.beeware.org/en/latest/tutorial/tutorial-5/android.html

**Comment by kvonosan** [comment]
on windows 10 the template doesn't support Python 3.10 projects too.

**Comment by freakboy3742** [comment]
Thanks for the report. The underlying problem is that we don't have a support package for Python 3.10 yet.

**Comment by freakboy3742** [comment]
We have now published 3.10 support.
