### ISSUE TITLE
Extend LD_LIBRARY_PATH, rather than overwriting it

### ISSUE THREAD

**Issue by paulproteus** [beeware/briefcase-android-gradle-template#6]
pmp-p on BeeWare Gitter points out that overwriting LD_LIBRARY_PATH could conflict with the configuration provided by Android vendors. It's better to add to the LD_LIBRARY_PATH, rather than overwrite it:

https://github.com/beeware/briefcase-android-gradle-template/blob/c8b8c08026c1f4f841d9fbea3b4ef3b575381a0e/%7B%7B%20cookiecutter.formal_name%20%7D%7D/app/src/main/java/org/beeware/android/MainActivity.java#L111

If possible, I'd prefer not to set that environment variable at all.

**Comment by pmp-p** [comment]
> If possible, I'd prefer not to set that environment variable at all.

That's what i usually do, but i put all my libs ( especially the pip generated ones ) in the apk special lib folder : so i'm not sure if you won't need it for some dlopen() stuff later
