### ISSUE TITLE
When unpacking ZIP files, if the file hasn't changed, and it seems unpacked, don't unpack it

### ISSUE THREAD

**Issue by paulproteus** [beeware/briefcase-android-gradle-template#7]
This would speed up my iteration time.

**Comment by paulproteus** [comment]
#11 handles this for the Python stdlib. The other ZIP files are probably smaller, and are also harder to cache this way, so that's as far as #11 goes for now.

**Comment by freakboy3742** [comment]
Closing for now; we can revisit this as a performance boost if it's necessary.
