### ISSUE TITLE
androidx.fragment:fragment version warning from Google Play

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase-android-gradle-template#76]
*Originally posted by @t-arn on Discord*

-----

Hello apiarists, I just published a new version of pyPlayground to Google Play and got following warning:

![fragment](https://github.com/beeware/briefcase-android-gradle-template/assets/166954/0f857a88-ee3e-4c32-8f4b-74d9f7e60854)

It means that the androidx.fragment:fragment SDK Version (1.0.0) is outdated and that we should update to 1.1.0

**Comment by mhsmith** [comment]
The warning is probably harmless, but we should fix it if we can. This library will be a dependency of `androidx.appcompat:appcompat` in app/build.gradle.td

**Comment by freakboy3742** [comment]
I believe this has been indirectly fixed by the release of Briefcase 0.3.17, which makes the list of libraries configurable, and now defaults to appcompat 1.6.1 (and thus fragment 1.3.6).
